# GoReleaser 설정
# 사용법:
#   로컬 테스트: goreleaser build --snapshot --clean
#   릴리스: git tag v0.5.0 && git push origin v0.5.0 && goreleaser release --clean
#
# 참고: https://goreleaser.com/

project_name: whatap-go-inst

# before hooks disabled - go.mod is pre-configured

builds:
  # 공식 바이너리
  - id: whatap-go-inst
    main: ./cmd/whatap-go-inst
    binary: whatap-go-inst
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/whatap/go-api-inst/cmd.Version={{.Version}}
      - -X github.com/whatap/go-api-inst/cmd.GitCommit={{.Commit}}
      - -X github.com/whatap/go-api-inst/cmd.BuildDate={{.Date}}

  # 단축 바이너리
  - id: goinst
    main: ./cmd/goinst
    binary: goinst
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/whatap/go-api-inst/cmd.Version={{.Version}}
      - -X github.com/whatap/go-api-inst/cmd.GitCommit={{.Commit}}
      - -X github.com/whatap/go-api-inst/cmd.BuildDate={{.Date}}

archives:
  - id: whatap-go-inst-archive
    builds:
      - whatap-go-inst
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

  - id: goinst-archive
    builds:
      - goinst
    format: tar.gz
    name_template: "goinst_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: whatap
    name: go-api-inst
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
