package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
)

var unpinCmd = &cobra.Command{
	Use:   "uninit",
	Short: "Remove files added by init command",
	Long: `Removes instrumentation-related files added by whatap-go-inst init.

Files removed:
  - whatap_inst.tool.go
  - whatap_inst_generate.go

Usage:
  whatap-go-inst uninit`,
	Run: func(cmd *cobra.Command, args []string) {
		dir := "."
		if len(args) > 0 {
			dir = args[0]
		}

		count, err := unpinProject(dir)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}

		if count == 0 {
			fmt.Println("No files to remove.")
		} else {
			fmt.Printf("%d file(s) removed.\n", count)
		}
	},
}

// unpinProject removes files generated by embed
func unpinProject(dir string) (int, error) {
	count := 0

	// Target file patterns (new patterns + legacy patterns)
	targetPatterns := []string{
		"whatap_inst.tool.go",
		"whatap_inst_generate.go",
		"go_api_ast.tool.go",     // backward compatibility
		"go_api_ast_generate.go", // backward compatibility
	}

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			return nil
		}

		// Delete target files
		filename := filepath.Base(path)
		for _, pattern := range targetPatterns {
			if filename == pattern {
				fmt.Printf("Removed: %s\n", path)
				if err := os.Remove(path); err != nil {
					return err
				}
				count++
				break
			}
		}

		return nil
	})

	return count, err
}

func init() {
	rootCmd.AddCommand(unpinCmd)
}
