package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// Subcommands removed in v0.5.5 are kept as hidden stubs that print a
// migration guide and exit non-zero. Without these, cobra silently falls
// back to root help with exit 0, hiding the breaking change from CI and
// shell scripts. See §234 Phase 5 (inject/generate) and §245 (init/uninit).

const (
	deprecatedInitHint = `The build wrapper now adds dependencies, injects instrumentation, and
builds in a single step:

  whatap-go-inst go build ./...

If your project still has the files generated by the old 'init' command,
remove them once:

  rm whatap_inst.tool.go whatap_inst_generate.go`

	deprecatedUninitHint = `Removed in v0.5.5 alongside 'init' (§245). The build wrapper no longer
generates whatap_inst.tool.go / whatap_inst_generate.go, so there is
nothing to clean. To remove leftovers from a v0.5.4 install:

  rm whatap_inst.tool.go whatap_inst_generate.go`

	deprecatedInjectHint = `Use the build wrapper with --output to dump the transformed source while
building:

  whatap-go-inst --output=./instrumented go build ./...

The originals are never modified, so a follow-up 'remove' pass is not
needed. (§234 Phase 5)`

	deprecatedGenerateHint = `Removed in v0.5.5 (§234 Phase 5). The build wrapper instruments at
toolexec time and does not need a 'go:generate' step:

  whatap-go-inst go build ./...`
)

func newDeprecatedCmd(name, hint string) *cobra.Command {
	return &cobra.Command{
		Use:                name,
		Short:              "(removed in v0.5.5)",
		Hidden:             true,
		DisableFlagParsing: true,
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Fprintf(os.Stderr,
				"Error: 'whatap-go-inst %s' was removed in v0.5.5.\n\n%s\n",
				name, hint)
			os.Exit(1)
		},
	}
}

func init() {
	rootCmd.AddCommand(
		newDeprecatedCmd("init", deprecatedInitHint),
		newDeprecatedCmd("uninit", deprecatedUninitHint),
		newDeprecatedCmd("inject", deprecatedInjectHint),
		newDeprecatedCmd("generate", deprecatedGenerateHint),
	)
}
