package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/whatap/go-api-inst/ast"

	"github.com/spf13/cobra"
)

var pinCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize project for whatap instrumentation",
	Long: `Analyzes the project and generates files required for whatap instrumentation.

Behavior:
  1. Analyze project source → detect frameworks in use
  2. Generate whatap_inst.tool.go file (whatap import declarations)
  3. Generate whatap_inst_generate.go file (go:generate directive)
  4. Run go mod tidy (automatically add dependencies)

Usage:
  1. Run in go.mod directory:
     whatap-go-inst init

  2. Commit changes (optional):
     git add go.mod go.sum whatap_inst.tool.go whatap_inst_generate.go
     git commit -m "chore: enable whatap instrumentation"

  3. Build (choose one):
     whatap-go-inst go build ./...
     or
     go generate ./... && go build ./...`,
	Run: func(cmd *cobra.Command, args []string) {
		dir := "."
		if len(args) > 0 {
			dir = args[0]
		}

		if err := pinProject(dir); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
	},
}

// pinProject adds whatap dependencies to project
func pinProject(dir string) error {
	fmt.Println("Analyzing project...")

	// 1. Analyze project to detect frameworks in use
	frameworks, err := analyzeProject(dir)
	if err != nil {
		return fmt.Errorf("project analysis failed: %w", err)
	}

	if len(frameworks) == 0 {
		fmt.Println("No frameworks detected.")
		fmt.Println("Adding only the basic trace package.")
	} else {
		fmt.Printf("Detected frameworks: %v\n", frameworks)
	}

	// 2. Generate whatap_inst.tool.go file
	toolFile := filepath.Join(dir, "whatap_inst.tool.go")
	if err := generateToolFile(toolFile, frameworks); err != nil {
		return fmt.Errorf("tool file generation failed: %w", err)
	}
	fmt.Printf("Created: %s\n", toolFile)

	// 3. Generate whatap_inst_generate.go file (for go:generate)
	generateFile := filepath.Join(dir, "whatap_inst_generate.go")
	if err := generateGenerateFile(generateFile); err != nil {
		return fmt.Errorf("generate file creation failed: %w", err)
	}
	fmt.Printf("Created: %s\n", generateFile)

	fmt.Println("\n✓ Done!")
	fmt.Println("\nNext steps:")
	fmt.Println("  1. Add dependency and update go.mod:")
	fmt.Println("     go get github.com/whatap/go-api@latest")
	fmt.Println("     go mod tidy")
	fmt.Println()
	fmt.Println("  2. Build:")
	fmt.Println("     whatap-go-inst go build ./...")

	return nil
}

// analyzeProject analyzes project and returns frameworks in use
func analyzeProject(dir string) ([]ast.Framework, error) {
	analyzer := ast.NewAnalyzer()
	var frameworks []ast.Framework
	seen := make(map[string]bool)

	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil // Ignore error and continue
		}

		// Directory skip conditions
		if info.IsDir() {
			base := filepath.Base(path)
			if base == "vendor" || base == ".git" || base == "node_modules" || base == "testapps" {
				return filepath.SkipDir
			}
			return nil
		}

		// Process only .go files
		if filepath.Ext(path) != ".go" {
			return nil
		}

		// Skip generated files
		if strings.Contains(path, "whatap_inst") || strings.Contains(path, "go_api_ast") {
			return nil
		}

		// Skip _test.go files
		if strings.HasSuffix(path, "_test.go") {
			return nil
		}

		// Analyze file
		result, err := analyzer.AnalyzeFile(path)
		if err != nil {
			return nil // Ignore error and continue
		}

		// Add detected frameworks
		for _, fw := range result.Frameworks {
			if !seen[fw.Name] {
				seen[fw.Name] = true
				frameworks = append(frameworks, fw)
			}
		}

		return nil
	})

	return frameworks, err
}

// generateToolFile generates tool file containing whatap imports
// All packages must be directly imported (not via instrumentation/all)
// because toolexec mode requires direct dependencies for .a file paths
func generateToolFile(path string, frameworks []ast.Framework) error {
	content := `// Code generated by whatap-go-inst init; DO NOT EDIT.
// This file declares whatap instrumentation dependencies.
// All packages are directly imported for toolexec mode compatibility.

//go:build whatap_tools

package main

import (
	// Standard library (used by injected code)
	_ "context"
	_ "os"

	// Core whatap packages
	_ "github.com/whatap/go-api/httpc"
	_ "github.com/whatap/go-api/logsink"
	_ "github.com/whatap/go-api/trace"

	// Web frameworks
	_ "github.com/whatap/go-api/instrumentation/github.com/gin-gonic/gin/whatapgin"
	_ "github.com/whatap/go-api/instrumentation/github.com/go-chi/chi/whatapchi"
	_ "github.com/whatap/go-api/instrumentation/github.com/gofiber/fiber/v2/whatapfiber"
	_ "github.com/whatap/go-api/instrumentation/github.com/gorilla/mux/whatapmux"
	_ "github.com/whatap/go-api/instrumentation/github.com/labstack/echo/v4/whatapecho"
	_ "github.com/whatap/go-api/instrumentation/github.com/labstack/echo/whatapecho"
	_ "github.com/whatap/go-api/instrumentation/github.com/valyala/fasthttp/whatapfasthttp"
	_ "github.com/whatap/go-api/instrumentation/net/http/whataphttp"

	// Database
	_ "github.com/whatap/go-api/instrumentation/database/sql/whatapsql"
	_ "github.com/whatap/go-api/instrumentation/github.com/go-gorm/gorm/whatapgorm"
	_ "github.com/whatap/go-api/instrumentation/github.com/jinzhu/gorm/whatapgorm"
	_ "github.com/whatap/go-api/instrumentation/github.com/jmoiron/sqlx/whatapsqlx"

	// External services
	_ "github.com/whatap/go-api/instrumentation/github.com/IBM/sarama/whatapsarama"
	_ "github.com/whatap/go-api/instrumentation/github.com/Shopify/sarama/whatapsarama"
	_ "github.com/whatap/go-api/instrumentation/github.com/aerospike/aerospike-client-go/v6/whatapas"
	_ "github.com/whatap/go-api/instrumentation/github.com/go-redis/redis/v8/whatapgoredis"
	_ "github.com/whatap/go-api/instrumentation/github.com/gomodule/redigo/whatapredigo"
	_ "github.com/whatap/go-api/instrumentation/github.com/redis/go-redis/v9/whatapgoredis"
	_ "github.com/whatap/go-api/instrumentation/go.mongodb.org/mongo-driver/mongo/whatapmongo"

	// RPC & Cloud
	_ "github.com/whatap/go-api/instrumentation/google.golang.org/grpc/whatapgrpc"
	_ "github.com/whatap/go-api/instrumentation/k8s.io/client-go/kubernetes/whatapkubernetes"

	// Log libraries
	_ "github.com/whatap/go-api/instrumentation/fmt/whatapfmt"
)
`
	return os.WriteFile(path, []byte(content), 0644)
}

// generateGenerateFile generates go:generate directive file
func generateGenerateFile(path string) error {
	// Skip if already exists
	if _, err := os.Stat(path); err == nil {
		return nil
	}

	content := `// Code generated by whatap-go-inst embed; DO NOT EDIT.

//go:generate whatap-go-inst generate

package main
`
	return os.WriteFile(path, []byte(content), 0644)
}

// getWhatapImportForFramework returns whatap import path for framework
func getWhatapImportForFramework(fw ast.Framework) string {
	switch fw.Name {
	case "gin":
		return `"github.com/whatap/go-api/instrumentation/github.com/gin-gonic/gin/whatapgin"`
	case "echo":
		if strings.Contains(fw.ImportPath, "/v4") {
			return `"github.com/whatap/go-api/instrumentation/github.com/labstack/echo/v4/whatapecho"`
		}
		return `"github.com/whatap/go-api/instrumentation/github.com/labstack/echo/whatapecho"`
	case "fiber":
		if strings.Contains(fw.ImportPath, "/v2") {
			return `"github.com/whatap/go-api/instrumentation/github.com/gofiber/fiber/v2/whatapfiber"`
		}
		return `"github.com/whatap/go-api/instrumentation/github.com/gofiber/fiber/whatapfiber"`
	case "chi":
		return `"github.com/whatap/go-api/instrumentation/github.com/go-chi/chi/whatapchi"`
	case "gorilla":
		return `"github.com/whatap/go-api/instrumentation/github.com/gorilla/mux/whatapmux"`
	case "nethttp":
		return `"github.com/whatap/go-api/instrumentation/net/http/whataphttp"`
	case "fasthttp":
		return `"github.com/whatap/go-api/instrumentation/github.com/valyala/fasthttp/whatapfasthttp"`
	case "sql":
		return `"github.com/whatap/go-api/instrumentation/database/sql/whatapsql"`
	case "gorm":
		return `"github.com/whatap/go-api/instrumentation/github.com/go-gorm/gorm/whatapgorm"`
	case "redigo":
		return `"github.com/whatap/go-api/instrumentation/github.com/gomodule/redigo/whatapredigo"`
	case "sarama":
		if strings.Contains(fw.ImportPath, "IBM") {
			return `"github.com/whatap/go-api/instrumentation/github.com/IBM/sarama/whatapsarama"`
		}
		return `"github.com/whatap/go-api/instrumentation/github.com/Shopify/sarama/whatapsarama"`
	}
	return ""
}

// runGoGet runs go get for instrumentation/all package
// This adds go-api and all its instrumentation dependencies to go.mod
func runGoGet(dir string) error {
	cmd := exec.Command("go", "get", "github.com/whatap/go-api/instrumentation/all@latest")
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

// runGoModTidy runs go mod tidy
func runGoModTidy(dir string) error {
	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func init() {
	rootCmd.AddCommand(pinCmd)
}
